name = "sample-integration"
version = "0.1.0"
description = "Sample Integration"


include = ["cannonfile.toml"]

[contract.sample_integration]
artifact = "SampleIntegration"
args = [
    "<%= imports.synthetix.contracts.CoreProxy.address %>",
    "<%= imports.synthetix.contracts.USDProxy.address %>",
]
depends = ["provision.synthetix"]

[setting.prize]
defaultValue = "1000000000000000000000"

[setting.ticketCost]
defaultValue = "1000000000000000000"

[setting.feePercent]
defaultValue = "10000000000000000"

[setting.salt]
defaultValue = "snax"

[import.vrf]
source = "chainlink-vrf:2.0.0"

[contract.NumberGuessingGame]
artifact = "NumberGuessingGame"
create2 = true
args = [
    "<%= imports.synthetix.contracts.CoreProxy.address %>",
    "<%= imports.vrf.imports.linkAggregator.imports.linkToken.contracts.Token.address %>",
    "<%= imports.vrf.contracts.VRFWrapper.address %>",
    "<%= settings.prize %>",
    "<%= settings.ticketCost %>",
    "<%= settings.feePercent %>"
]
depends = ["import.vrf", "provision.synthetix"]

## Problem Code Below

# [invoke.registerMarket]
# target = ["NumberGuessingGame"]
# func = "registerMarket"
# extra.marketId.event = "MarketRegistered"
# extra.marketId.arg = 0
# depends = ["contract.NumberGuessingGame", "invoke.allowAllRegisterMarket"]
