[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# this additional config is required when using cannon with foundry
fs_permissions = [{ access = "read", path = "./" }]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config